// International dialing codes for phone country-code selector with 2-letter ISO codes for flag images
export const COUNTRY_CODES = [
  { code: '+86', country: 'China', iso: 'cn' },
  { code: '+91', country: 'India', iso: 'in' },
  { code: '+852', country: 'Hong Kong', iso: 'hk' },
  { code: '+853', country: 'Macau', iso: 'mo' },
  { code: '+886', country: 'Taiwan', iso: 'tw' },
  { code: '+65', country: 'Singapore', iso: 'sg' },
  { code: '+60', country: 'Malaysia', iso: 'my' },
  { code: '+1', country: 'US / Canada', iso: 'us' },
  { code: '+44', country: 'United Kingdom', iso: 'gb' },
  { code: '+81', country: 'Japan', iso: 'jp' },
  { code: '+82', country: 'South Korea', iso: 'kr' },
  { code: '+61', country: 'Australia', iso: 'au' },
  { code: '+64', country: 'New Zealand', iso: 'nz' },
  { code: '+66', country: 'Thailand', iso: 'th' },
  { code: '+84', country: 'Vietnam', iso: 'vn' },
  { code: '+63', country: 'Philippines', iso: 'ph' },
  { code: '+62', country: 'Indonesia', iso: 'id' },
  { code: '+95', country: 'Myanmar', iso: 'mm' },
  { code: '+977', country: 'Nepal', iso: 'np' },
  { code: '+94', country: 'Sri Lanka', iso: 'lk' },
  { code: '+92', country: 'Pakistan', iso: 'pk' },
  { code: '+880', country: 'Bangladesh', iso: 'bd' },
  { code: '+971', country: 'UAE', iso: 'ae' },
  { code: '+966', country: 'Saudi Arabia', iso: 'sa' },
  { code: '+974', country: 'Qatar', iso: 'qa' },
  { code: '+973', country: 'Bahrain', iso: 'bh' },
  { code: '+965', country: 'Kuwait', iso: 'kw' },
  { code: '+968', country: 'Oman', iso: 'om' },
  { code: '+962', country: 'Jordan', iso: 'jo' },
  { code: '+972', country: 'Israel', iso: 'il' },
  { code: '+90', country: 'Turkey', iso: 'tr' },
  { code: '+7', country: 'Russia', iso: 'ru' },
  { code: '+33', country: 'France', iso: 'fr' },
  { code: '+49', country: 'Germany', iso: 'de' },
  { code: '+39', country: 'Italy', iso: 'it' },
  { code: '+34', country: 'Spain', iso: 'es' },
  { code: '+31', country: 'Netherlands', iso: 'nl' },
  { code: '+32', country: 'Belgium', iso: 'be' },
  { code: '+41', country: 'Switzerland', iso: 'ch' },
  { code: '+43', country: 'Austria', iso: 'at' },
  { code: '+46', country: 'Sweden', iso: 'se' },
  { code: '+47', country: 'Norway', iso: 'no' },
  { code: '+45', country: 'Denmark', iso: 'dk' },
  { code: '+358', country: 'Finland', iso: 'fi' },
  { code: '+351', country: 'Portugal', iso: 'pt' },
  { code: '+30', country: 'Greece', iso: 'gr' },
  { code: '+353', country: 'Ireland', iso: 'ie' },
  { code: '+48', country: 'Poland', iso: 'pl' },
  { code: '+420', country: 'Czech Republic', iso: 'cz' },
  { code: '+36', country: 'Hungary', iso: 'hu' },
  { code: '+40', country: 'Romania', iso: 'ro' },
  { code: '+27', country: 'South Africa', iso: 'za' },
  { code: '+20', country: 'Egypt', iso: 'eg' },
  { code: '+234', country: 'Nigeria', iso: 'ng' },
  { code: '+254', country: 'Kenya', iso: 'ke' },
  { code: '+55', country: 'Brazil', iso: 'br' },
  { code: '+52', country: 'Mexico', iso: 'mx' },
  { code: '+54', country: 'Argentina', iso: 'ar' },
  { code: '+56', country: 'Chile', iso: 'cl' },
  { code: '+57', country: 'Colombia', iso: 'co' },
  { code: '+51', country: 'Peru', iso: 'pe' },
  { code: '+58', country: 'Venezuela', iso: 've' },
];

// Comprehensive list of countries with 2-letter ISO codes for real flag images
export const ALL_COUNTRIES = [
  { name: 'China', iso: 'cn' },
  { name: 'India', iso: 'in' },
  { name: 'Hong Kong', iso: 'hk' },
  { name: 'Macau', iso: 'mo' },
  { name: 'Taiwan', iso: 'tw' },
  { name: 'Singapore', iso: 'sg' },
  { name: 'Malaysia', iso: 'my' },
  { name: 'Thailand', iso: 'th' },
  { name: 'Nepal', iso: 'np' },
  { name: 'Sri Lanka', iso: 'lk' },
  { name: 'Vietnam', iso: 'vn' },
  { name: 'Indonesia', iso: 'id' },
  { name: 'Myanmar', iso: 'mm' },
  { name: 'Japan', iso: 'jp' },
  { name: 'South Korea', iso: 'kr' },
  { name: 'United States', iso: 'us' },
  { name: 'Canada', iso: 'ca' },
  { name: 'United Kingdom', iso: 'gb' },
  { name: 'Australia', iso: 'au' },
  { name: 'New Zealand', iso: 'nz' },
  { name: 'Germany', iso: 'de' },
  { name: 'France', iso: 'fr' },
  { name: 'Italy', iso: 'it' },
  { name: 'Spain', iso: 'es' },
  { name: 'Switzerland', iso: 'ch' },
  { name: 'Netherlands', iso: 'nl' },
  { name: 'Belgium', iso: 'be' },
  { name: 'Sweden', iso: 'se' },
  { name: 'Norway', iso: 'no' },
  { name: 'Denmark', iso: 'dk' },
  { name: 'Finland', iso: 'fi' },
  { name: 'Austria', iso: 'at' },
  { name: 'Portugal', iso: 'pt' },
  { name: 'Greece', iso: 'gr' },
  { name: 'Ireland', iso: 'ie' },
  { name: 'Poland', iso: 'pl' },
  { name: 'Russia', iso: 'ru' },
  { name: 'United Arab Emirates', iso: 'ae' },
  { name: 'Saudi Arabia', iso: 'sa' },
  { name: 'Qatar', iso: 'qa' },
  { name: 'Kuwait', iso: 'kw' },
  { name: 'Oman', iso: 'om' },
  { name: 'Turkey', iso: 'tr' },
  { name: 'Egypt', iso: 'eg' },
  { name: 'South Africa', iso: 'za' },
  { name: 'Brazil', iso: 'br' },
  { name: 'Mexico', iso: 'mx' },
  { name: 'Argentina', iso: 'ar' },
  { name: 'Chile', iso: 'cl' },
  { name: 'Colombia', iso: 'co' },
  { name: 'Peru', iso: 'pe' },
  { name: 'Other', iso: 'un' }
];

export const isValidCountryCode = (code) => COUNTRY_CODES.some((c) => c.code === code);
