// International dialing codes for the phone country-code selector (FE-11).
// Mirrors server/utils/countryCodes.js so frontend and backend never disagree.
export const COUNTRY_CODES = [
  { code: '+86', label: 'China 中国' },
  { code: '+91', label: 'India' },
  { code: '+852', label: 'Hong Kong' },
  { code: '+853', label: 'Macau' },
  { code: '+886', label: 'Taiwan' },
  { code: '+65', label: 'Singapore' },
  { code: '+60', label: 'Malaysia' },
  { code: '+1', label: 'US / Canada' },
  { code: '+44', label: 'United Kingdom' },
  { code: '+81', label: 'Japan' },
  { code: '+82', label: 'South Korea' },
  { code: '+61', label: 'Australia' },
  { code: '+64', label: 'New Zealand' },
  { code: '+66', label: 'Thailand' },
  { code: '+84', label: 'Vietnam' },
  { code: '+63', label: 'Philippines' },
  { code: '+62', label: 'Indonesia' },
  { code: '+95', label: 'Myanmar' },
  { code: '+977', label: 'Nepal' },
  { code: '+94', label: 'Sri Lanka' },
  { code: '+92', label: 'Pakistan' },
  { code: '+880', label: 'Bangladesh' },
  { code: '+971', label: 'UAE' },
  { code: '+966', label: 'Saudi Arabia' },
  { code: '+974', label: 'Qatar' },
  { code: '+973', label: 'Bahrain' },
  { code: '+965', label: 'Kuwait' },
  { code: '+968', label: 'Oman' },
  { code: '+962', label: 'Jordan' },
  { code: '+972', label: 'Israel' },
  { code: '+90', label: 'Turkey' },
  { code: '+7', label: 'Russia' },
  { code: '+33', label: 'France' },
  { code: '+49', label: 'Germany' },
  { code: '+39', label: 'Italy' },
  { code: '+34', label: 'Spain' },
  { code: '+31', label: 'Netherlands' },
  { code: '+32', label: 'Belgium' },
  { code: '+41', label: 'Switzerland' },
  { code: '+43', label: 'Austria' },
  { code: '+46', label: 'Sweden' },
  { code: '+47', label: 'Norway' },
  { code: '+45', label: 'Denmark' },
  { code: '+358', label: 'Finland' },
  { code: '+351', label: 'Portugal' },
  { code: '+30', label: 'Greece' },
  { code: '+353', label: 'Ireland' },
  { code: '+48', label: 'Poland' },
  { code: '+420', label: 'Czech Republic' },
  { code: '+36', label: 'Hungary' },
  { code: '+40', label: 'Romania' },
  { code: '+27', label: 'South Africa' },
  { code: '+20', label: 'Egypt' },
  { code: '+234', label: 'Nigeria' },
  { code: '+254', label: 'Kenya' },
  { code: '+55', label: 'Brazil' },
  { code: '+52', label: 'Mexico' },
  { code: '+54', label: 'Argentina' },
  { code: '+56', label: 'Chile' },
  { code: '+57', label: 'Colombia' },
  { code: '+51', label: 'Peru' },
  { code: '+58', label: 'Venezuela' },
];

export const isValidCountryCode = (code) => COUNTRY_CODES.some((c) => c.code === code);
